# Generated by Django 4.2.16 on 2026-03-31 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, default='', verbose_name='内容')),
                ('image', models.ImageField(blank=True, null=True, upload_to='chat_images/%Y/%m/', verbose_name='图片')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '讨论消息',
                'verbose_name_plural': '讨论消息',
                'db_table': 'message',
                'ordering': ['created_at'],
            },
        ),
    ]
