# Generated by Django 4.2.16 on 2026-04-16 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='github_id',
            field=models.PositiveBigIntegerField(blank=True, null=True, unique=True, verbose_name='GitHub ID'),
        ),
    ]
