# Generated by Django 4.2.16 on 2026-03-31 15:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('refresh_interval', models.PositiveIntegerField(default=5, verbose_name='刷新间隔(分钟)')),
                ('is_active', models.BooleanField(default=True, verbose_name='进行中')),
            ],
            options={
                'verbose_name': '上课时段',
                'verbose_name_plural': '上课时段',
                'db_table': 'class_session',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='课程名称')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='EmojiReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='分数')),
                ('time_slot', models.PositiveIntegerField(default=0, verbose_name='时段编号')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='feedback.classsession')),
            ],
            options={
                'verbose_name': '表情反馈',
                'verbose_name_plural': '表情反馈',
                'db_table': 'emoji_reaction',
            },
        ),
    ]
